### ISSUE TITLE
Add benchmark: serde-rs/json

### ISSUE THREAD

**Issue by deeprobin** [simdjson/simdjson_website#1]
[serde-json](https://github.com/serde-rs/json) is a very fast library for Rust to parse JSON. I would like to know if simdjson is faster than serde-json, because Rust products are usually faster than C++¹, due to the ownership system.

[1]: [Rust vs C++ g++ Benchmark](https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/rust-gpp.html)

**Comment by lemire** [comment]
I will close this issue because this repository is the simdjson website.

> I would like to know if simdjson is faster than serde-json

I encourage you to run benchmarks.
