### ISSUE TITLE
debian package status link

### ISSUE THREAD

**Issue by cdluminate** [simdjson/simdjson_website#3]
This one is better compared to the current link on the software page: https://tracker.debian.org/pkg/simdjson
The current link only gives a view on the simdjson package in unstable, but the tracker.d.o link gives the overview across releases. The page also provides links to basically everything related to the package, including build status (and build logs), bugs, etc.

**Comment by lemire** [comment]
Fantastic

**Comment by lemire** [comment]
Updated. Thanks.
